name: mdreader
description: "A cross-platform read-only markdown viewer."
publish_to: 'none'
version: 2.0.2+3

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  markdown_widget: ^2.3.0
  shared_preferences: ^2.3.0
  file_picker: ^8.0.0
  window_manager: ^0.4.0
  printing: ^5.13.0
  pdf: ^3.11.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
